# @package model

# Pytorch Lightning module to instantiate
_target_: tsgrasp.net.lit_tsgraspnet.LitTSGraspNet

# Params for Pytorch module
model_cfg:
  backbone_model_name: "MinkUNet14A"
  D: 4
  backbone_out_dim: 128
  add_s_loss_coeff: 10
  bce_loss_coeff: 1
  width_loss_coeff: 1
  top_confidence_quantile: 0.25 # Only backprop this proportion of BCE losses
  use_parallel_add_s: False
  feature_dimension: 1
  pt_radius: 0.005
  grid_size: 0.005